export const HEADER_TEXT_SIS_FINAN = 'Sistema Financeiro';
export const HEADER_TEXT_RECEITAS = 'Receitas';
export const HEADER_TEXT_DESPESAS = 'Despesas';
export const HEADER_TEXT_BALANCO = 'Balanço';
export const HEADER_TEXT_DATA = 'Data';
export const HEADER_TEXT_CATEGORIA = 'Categoria';
export const HEADER_TEXT_TITULO = 'Titulo';
export const HEADER_TEXT_VALOR = 'Valor';
export const BUTTON_TEXT_ADICIONAR = 'Adicionar';
